"""Contain all the constants in the program"""

BLOCK_SIZE_DEFAULT = 10

MAP_WIDTH_DEFAULT = 40
MAP_HEIGHT_DEFAULT = 40

POPULATION_SIZE_DEFAULT = 400

START_POINT_DEFAULT = (1, 1)
GOAL_POINT_DEFAULT = (MAP_WIDTH_DEFAULT - 2, MAP_HEIGHT_DEFAULT - 2)

MUTATION_RATE_DEFAULT = 100

WALL_RATE_DEFAULT = 0

LIFE_TIME_DEFAULT = int((MAP_WIDTH_DEFAULT + MAP_HEIGHT_DEFAULT) * 2)

LEFT = (-1, 0)
UP = (0, -1)
RIGHT = (1, 0)
DOWN = (0, 1)

DIRECTION = [UP, DOWN, RIGHT, LEFT]
