"""Contain all the constants in the program"""

BLOCK_SIZE = 10

MAP_WIDTH = 15
MAP_HEIGHT = 15

POPULATION_SIZE = 64

GOAL = (MAP_WIDTH-2, MAP_HEIGHT-2)

MUTATION_RATE = 0.1

WALL_RATE = 0.2

DRAW_CIRCLE = 5

LIFE_TIME = MAP_WIDTH + MAP_WIDTH + int((MAP_WIDTH + MAP_HEIGHT) / 2)

FOODS_AMOUNT = 5
GAME_SPEED = 0.002

LEFT = (-1, 0)
UP = (0, -1)
RIGHT = (1, 0)
DOWN = (0, 1)

DIRECTION = [UP, DOWN, RIGHT, LEFT]
